name: SS58
on:
  schedule:
    - cron:  '15 4/6 * * *'

jobs:
  ss58:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: check
      env:
        CI_LOG: 123
      run: |
        # yarn install --immutable | grep -v 'YN0013'
   
